export const DEPT_LIST = [
  { key: 'chef',                 label: 'Kitchen Preparation',         type: 'simple' },
  { key: 'tagPrints',            label: 'Tag Print',                   type: 'simple' },
  { key: 'dress',                label: 'Dress',                       type: 'simple' },
  { key: 'decor',                label: 'Decor List',                  type: 'simple' },
  { key: 'crockery',             label: 'Crockery List',               type: 'simple' },
  { key: 'kitchenRawMaterial',   label: 'Menu Kitchen Requirement',    type: 'simple' },
  { key: 'vegetables',           label: 'Vegetables',                  type: 'vegetables' },
  { key: 'cheeseDairy',          label: 'Cheese & Dairy Products',     type: 'cheeseDairy' },
  { key: 'vendorOrders',         label: 'Vendor Orders',               type: 'simple' },
  { key: 'bakery',               label: 'Bakery',                      type: 'simple' },
  { key: 'iceWaterRequirement',  label: 'Ice & Water Requirement',     type: 'simple' },
  { key: 'loadingBoysAunties',   label: 'Loading Boys & Aunties',      type: 'simple' },
  { key: 'vehicleRequirement',   label: 'Vehicle Requirement',         type: 'simple' },
  { key: 'gasCylinder',          label: 'Gas Cylinder',                type: 'simple' },
  { key: 'freshFlowers',         label: 'Fresh Flowers',               type: 'simple' },
  { key: 'waiters',              label: 'Waiters',                     type: 'simple' },
  { key: 'outsourcingTeam',      label: 'Outsourcing Team Requirement', type: 'simple' },
];
